.github/workflows/manual-test-matrix-workflow.yaml
.github/workflows/scheduled-run-all-tests-workflow.yaml
packages/testsuite/cypress/e2e/test-configuration-subsystem-health.cy.ts

Add tests for health subsystem configuration

Add tests for health subsystem configuration

---

README.md

more precise description of required environment variables used by podman

Podman usage description in README

---

.github/workflows/manual-test-matrix-workflow.yaml
.github/workflows/scheduled-run-all-tests-workflow.yaml
packages/testsuite/cypress/e2e/io/test-configuration-subsystem-io-buffer-pool.cy.ts
packages/testsuite/cypress/e2e/io/test-configuration-subsystem-io-worker.cy.ts
packages/testsuite/cypress/support/commands.ts

configuration io tests

---

.eslintrc.cjs
.github/workflows/manual-test-matrix-workflow.yaml
.github/workflows/scheduled-run-all-tests-workflow.yaml
packages/testsuite/cypress.config.ts
packages/testsuite/cypress/e2e/io/test-configuration-subsystem-io-buffer-pool.cy.ts
packages/testsuite/cypress/e2e/mail/test-configuration-subsystem-mail-attributes.cy.ts
packages/testsuite/cypress/e2e/mail/test-configuration-subsystem-mail-server.cy.ts
packages/testsuite/cypress/e2e/runtime/test-runtime-open-ports.cy.ts
packages/testsuite/cypress/e2e/runtime/test-runtime-server-status.cy.ts
packages/testsuite/cypress/support/resource-utils.ts

This PR adds coverage for runtime status view of the management console

Runtime server tests

---

.github/workflows/on-pull-request-workflow.yaml

Adds `npm run format` action and auto-commits the formatted files

Added auto-commit on PR workflow

---

README.md
packages/testsuite/cypress/e2e/distributable-web/test-configuration-subsystem-distributable-web-configuration.cy.ts
packages/testsuite/cypress/e2e/interface/test-configuration-interface.cy.ts
packages/testsuite/cypress/support/form-editing.ts

https://github.com/hal/berg/issues/44

[#44] Add Reset tests for known non-resetable configurations

---

packages/testsuite/cypress/e2e/datasource/test-configuration-datasource-mariadb-finder.cy.ts
packages/testsuite/cypress/e2e/datasource/test-configuration-datasource-mysql-finder.cy.ts
packages/testsuite/cypress/e2e/datasource/test-configuration-datasource-postgre-finder.cy.ts
packages/testsuite/cypress/e2e/datasource/test-configuration-datasource-sqlserver-finder.cy.ts

Do not check that
Local run:
```
(Run Finished)
│ ✔  test-configuration-datasource-maria      00:58        7        7        -        -        - │
│    db-finder.cy.ts                                                                             │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  test-configuration-datasource-mysql      01:04        7        7        -        -        - │
│    -finder.cy.ts                                                                               │
├─────────────────────────────────────────────────────────────── …
```

HAL-1850 driver module name is not rendered on page anymore

---

.github/workflows/on-pull-request-workflow.yaml
.github/workflows/scheduled-run-all-tests-workflow.yaml

Added write permissions for auto-commit task, added error handling on nightly jobs

Added write permissions for auto-commit task, added error handling on nightly jobs

---

.github/workflows/on-pull-request-workflow.yaml
packages/testsuite/cypress/support/form-editing.ts

This PR adds execution of changed test files into on PR workflow. I've included two test failures, that should reflect the CI execution and those test files shall be restored before merging this PR.

Added test trigger of changed files

---

packages/testsuite/cypress/e2e/distributable-web/test-configuration-subsystem-distributable-web-infinispan-session.cy.ts

Test to pass needs HAL console 3.6.9+ https://issues.redhat.com/browse/JBEAP-24970
Local run with HAL console 3.6.9
```
│ ✔  test-configuration-subsystem-distri      00:26        6        6        -        -        - │
│    butable-web-infinispan-session.cy.t                                                         │
│    s                                                                                           │
✔  All specs passed!                        00:26        6        6        -        - …
```

[JBEAP-24997] Adjust distributable web test to use composite operation

---

packages/berg/src/berg.ts
packages/testsuite/cypress.config.ts
packages/testsuite/cypress/e2e/datasource/test-configuration-datasource-mariadb-finder.cy.ts
packages/testsuite/cypress/e2e/datasource/test-configuration-datasource-postgre-finder.cy.ts
packages/testsuite/cypress/e2e/datasource/test-configuration-datasource-postgre.cy.ts
packages/testsuite/cypress/e2e/datasource/test-configuration-datasource-sqlserver-finder.cy.ts
packages/testsuite/cypress/support/containers-utils.ts

```
REPOSITORY                                                                                                      TAG                                                               IMAGE ID      CREATED        SIZE
quay.io/halconsole/wildfly-development                                                                          latest                                                            20fefee1e14d  7 hours ago    1 GB
quay.io/halconsole/hal-development                                                                              latest                                                            f6369ad78cf6  4 days ago     129 MB
docker.io/library/mariadb                                                                                       latest …
```

Tweak pulling images timeouts

---

packages/testsuite/cypress/e2e/homepage/test-homepage.cy.ts

Local run
```
(Run Finished)
│ ✔  test-homepage.cy.ts                      00:16        6        6        -        -        - │
✔  All specs passed!                        00:16        6        6        -        -        -  
```

In 3.6.10.SNAPSHOT link is called update-manager

---

packages/testsuite/cypress/e2e/elytron/test-configuration-subsystem-elytron-global-settings.cy.ts
packages/testsuite/cypress/support/form-editing.ts

I have added some artificial unnecessary action to slow down processing and avoid JBEAP-25005. This is similar to `cy.wait` after all.

[JBEAP-25005] wait for elytron global settings page to be loaded

---

.github/workflows/manual-test-matrix-workflow.yaml
.github/workflows/scheduled-run-all-tests-workflow.yaml
packages/testsuite/cypress/e2e/undertow/test-configuration-subsystem-undertow-global-settings.cy.ts
packages/testsuite/cypress/support/form-editing.ts
packages/testsuite/cypress/support/resource-utils.ts
packages/testsuite/cypress/support/verification-utils.ts

https://github.com/hal/berg/issues/37
Transfer of tests from legacy TS at: https://github.com/hal/testsuite.next/blob/master/tests-configuration-undertow/src/test/java/org/jboss/hal/testsuite/test/configuration/undertow/GlobalSettingsTest.java

Undertow global settings

---

README.md
package.json
packages/testsuite/cypress.config.ts
packages/testsuite/cypress/e2e/elytron-oidc-client/test-oidc-security-rbac.cy.ts
packages/testsuite/cypress/e2e/elytron-oidc-client/test-oidc-security.cy.ts
packages/testsuite/cypress/fixtures/realm-configuration.json
packages/testsuite/cypress/support/containers-utils.ts
packages/testsuite/cypress/support/navigation.ts
packages/testsuite/cypress/support/verification-utils.ts

Base test to verify the web-console can be secured by OIDC

EAP7-1796 - Add the ability to secure the management console with OIDC

---

package.json
packages/berg/src/berg.ts
packages/testsuite/cypress.config.ts

- Update version of Test Containers to 10.2.1
- log only useful information
nightly test run: https://github.com/hal/berg/actions/runs/5958148983
test run with update: https://github.com/kstekovi/berg/actions/runs/5965381856

Version and logging update

---

.github/workflows/manual-test-matrix-workflow.yaml
.github/workflows/scheduled-run-all-tests-workflow.yaml

enable elytron-oidc-client tests for github actions.
test run with  elytron-oidc-client enabled: https://github.com/kstekovi/berg/actions/runs/6001225816

enable oidc tests

---

packages/testsuite/cypress/e2e/elytron-oidc-client/test-oidc-security-configure-oidc.cy.ts
packages/testsuite/cypress/e2e/elytron-oidc-client/test-oidc-security-rbac.cy.ts
packages/testsuite/cypress/e2e/elytron-oidc-client/test-oidc-security.cy.ts
packages/testsuite/cypress/fixtures/realm-configuration.json
packages/testsuite/cypress/support/containers-utils.ts
packages/testsuite/cypress/support/form-editing.ts
packages/testsuite/cypress/support/navigation.ts

https://issues.redhat.com/browse/HAL-1832

EAP7-2012 Activate OIDC in the console

---

packages/testsuite/cypress/e2e/distributable-web/test-configuration-subsystem-distributable-web-routing.cy.ts
packages/testsuite/cypress/e2e/elytron-oidc-client/test-oidc-security-configure-oidc.cy.ts
packages/testsuite/cypress/support/form-editing.ts
packages/testsuite/cypress/support/verification-utils.ts

force select a value in select and close alert popup.

Stabilize the distributable web component tests.

---

packages/testsuite/cypress/e2e/distributable-web/test-configuration-subsystem-distributable-web-configuration.cy.ts
packages/testsuite/cypress/support/form-editing.ts

distrubutable web - remove reset test because the button was removed

distrubutable web - remove reset test because the button was removed

---

packages/testsuite/cypress.config.ts

Handle error better way and display useful information as reason

Handle error better way and display useful information as reason

---

packages/testsuite/cypress/e2e/ejb/test-configuration-subsystem-ejb-services-timer.cy.ts

https://issues.redhat.com/browse/HAL-1947

HAL-1947 Configuration -> EJB -> Services -> timer reset button display error pop-up notification: button removed

---

packages/testsuite/cypress.config.ts

https://issues.redhat.com/browse/HAL-1988

Adjusting WildFly container startup waiting condition

---

packages/testsuite/cypress/e2e/ejb/test-configuration-subsystem-ejb-container-remoting-profile.cy.ts
packages/testsuite/cypress/support/resource-utils.ts

Issue in test runs is currently shadowed by HAL-2025

[HAL-2026] Verify EJB profile reset spec

---

packages/testsuite/cypress/e2e/update-manager/test-configuration-update-channel.cy.ts
packages/testsuite/cypress/e2e/update-manager/test-update-custom-patch.cy.ts
packages/testsuite/cypress/e2e/update-manager/test-update-offline-archive.cy.ts
packages/testsuite/cypress/e2e/update-manager/test-update-online-and-revert-back.cy.ts

There are still 2 test failures on Firefox (timeouts?), although they pass when run in the Electron browser. However, I'm hesitant to switch all tests to Electron.

bugfix update manager
