.github/workflows/on-pull-request-workflow.yaml

This PR adds GH action CI workflow on opened pull request. This action performs `npm run lint` and `npm run compile` to make sure the submitted code is compilable and doesn't contain errors captured via `npm run lint`

GH action on Pull Request

---

packages/testsuite/cypress/e2e/deployment-scanner/test-configuration-subsystem-deployment-scanner.cy.ts

Replace with drop down menu value, e.g. jboss.server.base.dir
Local run
```
(Results)
│ Tests:        12                                                                               │
│ Passing:      12                                                                               │
│ Failing:      0                                                                                │
│ Pending:      0                                                                                │
│ Skipped:      0                                                                                │
│ Screenshots:  0                                                                                │
│ Video: …
```

Fixing relative-to test for Configuration => Subsystem => Deployment Scanner

---

packages/testsuite/cypress/e2e/distributable-web/test-configuration-subsystem-distributable-web-configuration.cy.ts

See https://issues.redhat.com/browse/JBEAP-24957 for details.

JBEAP-24957 Removing Reset test for Configuration => Subsystem => Distributable Web => Configuration

---

packages/testsuite/cypress.config.ts

Tried [`z` mode](https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label) option and it works. 
Local run of all tests using mount folder  `/home/fixtures`
```
(Run Finished)
│ ✔  core-management/test-configuration-      00:22        2        2        -        -        - │
│    subsystem-core-management-process-s                                                         │
│    tate-listener.cy.ts                                                                         │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔ …
```

Change settings of mount to be visible from container

---

packages/testsuite/cypress.config.ts
packages/testsuite/cypress/e2e/deployment-scanner/test-configuration-subsystem-deployment-scanner.cy.ts

Previous version was lagging to much
Local run:
```
│ ✔  test-configuration-subsystem-core-m      00:20        2        2        -        -        - │
│    anagement-process-state-listener.cy                                                         │
│    .ts                                                                                         │
✔  All specs passed!                        00:20        2        2        -        -        -  
```

Use nightly wildfly as we use nightly HAL.

---

packages/testsuite/cypress/e2e/ee/test-configuration-subsystem-ee-services-context-service.cy.ts

rendered anymore
Adjust test to new behaviour
Local run:
```
(Run Finished)
│ ✔  test-configuration-subsystem-ee-ser      00:21        4        4        -        -        - │
│    vices-context-service.cy.ts                                                                 │
✔  All specs passed!                        00:21        4        4        -        -        -  
```

WFLY-16705 use-transaction-setup-provider was deprecated and not

---

packages/testsuite/cypress/e2e/ejb/test-configuration-subsystem-ejb-container-container.cy.ts

Fields `default-entity-bean-instance-poo`,`default-entity-bean-optimistic-locking` are not shown in console. We can get rid of such fields from test as well.
https://docs.wildfly.org/28/wildscribe/subsystem/ejb3/index.html
Local run:
```
(Run Finished)
│ ✔  test-configuration-subsystem-ejb-co      01:14       20       20        -        -        - │
│    ntainer-container.cy.ts                                                                     │
✔  All specs passed!                        01:14 …
```

Entity beans are no more supported in WF 28

---

packages/testsuite/cypress/e2e/homepage/test-homepage.cy.ts

Patching is removed in EAP8.
It is replaced with Update Manager. Tracked by EAP7-1917
Local run
```
TESTS: Homepage
✓ Should display About info (9373ms)
✓ Should load Deployments page
✓ Should load Configuration page
✓ Should load Runtime page
Stopping container for test test_homepage
✓ Should load Access Control page
5 passing (14s)
[mochawesome] Report JSON saved to /home/mchoma/git-repo/berg/packages/testsuite/results/cypress/e2e/test-homepage_pass.json
(Results)
│ Tests:        5                                                                                │
│ Passing:      5                                                                                │
│ Failing:      0 …
```

Fix homepage

---

.github/workflows/manual-test-matrix-workflow.yaml
.github/workflows/scheduled-run-all-tests-workflow.yaml
packages/testsuite/cypress/e2e/homepage/test-homepage.cy.ts
packages/testsuite/cypress/e2e/update-manager/test-configuration-update-channel.cy.ts
packages/testsuite/cypress/e2e/update-manager/test-update-clean.cy.ts
packages/testsuite/cypress/e2e/update-manager/test-update-custom-patch.cy.ts
packages/testsuite/cypress/e2e/update-manager/test-update-offline-archive.cy.ts
packages/testsuite/cypress/e2e/update-manager/test-update-online-and-revert-back.cy.ts
packages/testsuite/cypress/support/navigation.ts

Hi, this PR adding test coverage for [EAP7-1984](https://issues.redhat.com/browse/EAP7-1984). It's cover added provisioning which was added in [HAL-1827](https://issues.redhat.com/browse/HAL-1827).
The added test coverage should be working only with EAP. When working with WildFly none of these pages should be visible.
[HAL-1827](https://issues.redhat.com/browse/HAL-1827) removing the update server by patch command and adding updating by installer command. This PR updating the homepage patch test to homepage update-manager test. This test will run only with EAP as with WildFly this should not be visible.
Adding test coverage for installer functions. That is online and offline update from channel, update by custom patch and add/remove/update channel. These test should be run only with EAP …

Add test for EAP7-1984

---

.github/workflows/manual-test-matrix-workflow.yaml
.github/workflows/scheduled-run-all-tests-workflow.yaml
packages/testsuite/cypress/e2e/metrics/test-configuration-subsystem-metrics.cy.ts
packages/testsuite/cypress/support/form-editing.ts

**Resources to cover**
Expected resources to cover from `/subsystem=metrics:read-resource(recursive=true):`
Fixes https://github.com/hal/berg/issues/13

Add tests for Metrics subsystem configuration

---

packages/berg/src/berg.ts
packages/testsuite/cypress.config.ts

To avoid undeterministic behaviour.
Details in https://java.testcontainers.org/features/advanced_options/
Local run
```
npm test -- --browser=chrome --specs="cypress/e2e/datasource/test-configuration-datasource-*.cy.ts"
...
====================================================================================================
(Run Finished)
│ ✔  test-configuration-datasource-maria      00:55        7        7        -        -        - │
│    db-finder.cy.ts                                                                             │
├──────────────────────────────────────────────────────────────────── …
```

Introduce usage of AlwaysPullPolicy when pulling images

---

packages/testsuite/cypress/e2e/runtime/test-runtime-server-status.cy.ts

1. on EAP it happens progress-bar is red - different name
2. closeTo with difference 1 is sometimes not enough
Local run:
```
│ ✔  test-runtime-server-status.cy.ts         00:18        5        5        -        -        - │
✔  All specs passed!                        00:18        5        5        -        -        -  
```

Make runtime-server-status tests more robust

---

packages/testsuite/cypress/e2e/update-manager/test-configuration-update-channel.cy.ts
packages/testsuite/cypress/e2e/update-manager/test-update-clean.cy.ts
packages/testsuite/cypress/e2e/update-manager/test-update-custom-patch.cy.ts
packages/testsuite/cypress/e2e/update-manager/test-update-offline-archive.cy.ts
packages/testsuite/cypress/e2e/update-manager/test-update-online-and-revert-back.cy.ts

Hi here is small update for update-manager module. Adding the help delay for form to load and change the timeout for updating the webconsole steps to make sure it will be executed correctly. Secondary update description of some test.
```
Spec                                                  Tests  Passing  Failing  Pending  Skipped  
│ ✔  test-configuration-update-channel.c      00:45        6        6        -        -        - │
│    y.ts                                                                                        │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  test-update-clean.cy.ts                  00:12        1 …
```

Adjust wait timing form update manager. Change description of two tests.

---

.github/workflows/manual-test-matrix-workflow.yaml
.github/workflows/scheduled-run-all-tests-workflow.yaml
packages/testsuite/cypress/e2e/security-manager/test-configuration-subsystem-security-manager-maximum-permissions.cy.ts
packages/testsuite/cypress/e2e/security-manager/test-configuration-subsystem-security-manager-minimum-permissions.cy.ts
packages/testsuite/cypress/support/form-editing.ts
packages/testsuite/cypress/support/navigation.ts
packages/testsuite/cypress/support/verification-utils.ts

Jira: [EAPQE-83](https://issues.redhat.com/browse/EAPQE-83)
Berg issue: #9 
Security Manager subsystem page contains "minimum permissions" and "maximum permissions" vertical navigation items, expecting two spec files to be created.
Resources to cover (from `/subsystem=securitymanager:read-resource(recursive=true)`):

Add security manager subsystem tests coverage

---

.github/workflows/manual-test-matrix-workflow.yaml
.github/workflows/scheduled-run-all-tests-workflow.yaml
packages/testsuite/cypress/e2e/transaction/transactions-configuration-subsystem-transaction-configuration.cy.ts
packages/testsuite/cypress/e2e/transaction/transactions-configuration-subsystem-transaction-finder.cy.ts
packages/testsuite/cypress/e2e/transaction/transactions-configuration-subsystem-transaction-jdbc.cy.ts
packages/testsuite/cypress/e2e/transaction/transactions-configuration-subsystem-transaction-path.cy.ts
packages/testsuite/cypress/e2e/transaction/transactions-configuration-subsystem-transaction-process.cy.ts
packages/testsuite/cypress/e2e/transaction/transactions-configuration-subsystem-transaction-recovery.cy.ts
packages/testsuite/cypress/support/resource-utils.ts

Possible follow-ups:
- form reset isn't being tested (from my tests it seems that the reset doesn't reset all attributes correctly)
- no coverage for invalid input values
- no coverage for invalid scenario for example when attribute cannot be set without other one
- no coverage for /subsystem=transactions/commit-markable-resource
- no coverage for /subsystem=transactions/log-store
Possible web console issue:
- Reset form doesn't seem to work
- I can't find how to add commit-markable-resource or log store. There is a "expert mode" in which it seems it should be possible to configure these but I can't make it work.
- It's possible to write non existing DS to [jdbc-store-datasource](https://docs.wildfly.org/28/wildscribe/subsystem/transactions/index.html#attr-jdbc-store-datasource) even …

[EAPQE-82][hal#34] Add transactions subsystem test coverage

---

packages/testsuite/cypress.config.ts

There are less timeout failures when increasing the `defaultCommandTimeout` basic config option value (from the default 4 seconds).

Increasing default timeout for commands

---

packages/testsuite/cypress/e2e/interface/test-configuration-interface.cy.ts

Remove reset form test because the field are not able to reset.

iterface doesnt have resetable fields

---

packages/testsuite/cypress.config.ts
packages/testsuite/cypress/e2e/elytron/test-configuration-subsystem-elytron-global-settings.cy.ts
packages/testsuite/cypress/e2e/jpa/test-configuration-subsystem-jpa.cy.ts
packages/testsuite/cypress/e2e/update-manager/test-configuration-update-channel.cy.ts
packages/testsuite/cypress/support/form-editing.ts

- Click on the edit button when is visible, 2 additional attempts.
- Don't log error message when it is verifying status of the Wildfly server
test run main:
https://github.com/kstekovi/berg/actions/runs/5832767352
test run edit-form:
https://github.com/kstekovi/berg/actions/runs/5940463851

Adding global workaround for test issues with edit form button

---

packages/testsuite/cypress.config.ts

- Verify the exit code of CLI operation. If the exit code is `0` then resolve the CLI operation. If the exit code isn't `0` then log output and reject the CLI operation. 
- use default `9990` port in case of network mode
nightly run: https://github.com/hal/berg/actions/runs/5994318213
test run: https://github.com/kstekovi/berg/actions/runs/5999872741

Update logging of CLI operations

---

packages/testsuite/cypress.config.ts
packages/testsuite/cypress/e2e/datasource/test-configuration-datasource-mariadb-finder.cy.ts
packages/testsuite/cypress/e2e/datasource/test-configuration-datasource-mysql-finder.cy.ts
packages/testsuite/cypress/e2e/datasource/test-configuration-datasource-postgre-finder.cy.ts
packages/testsuite/cypress/e2e/datasource/test-configuration-datasource-postgre.cy.ts
packages/testsuite/cypress/e2e/datasource/test-configuration-datasource-sqlserver-finder.cy.ts

new datasource module doesn't require dependency on `javax.transaction.api`

don't use `javax.transaction.api` 

---

packages/commands/src/add-data-source.ts
packages/testsuite/cypress/e2e/transaction/transactions-configuration-subsystem-transaction-jdbc.cy.ts
packages/testsuite/cypress/support/form-editing.ts

transaction - fix CLI command, close a suggestion for text input

transaction - fix CLI command, close a suggestion for text input

---

packages/testsuite/cypress/e2e/ee/test-configuration-subsystem-ee-services-context-service.cy.ts

The EE context service doesn't contain reset button anymore. 
Remove the reset button test.

remove ee context service reset test

---

packages/testsuite/cypress/e2e/ejb/test-configuration-subsystem-ejb-services-iiop.cy.ts

The reset button was removed in EJB subsystem for IIOP service.

remove ejb iiop service reset button test
